# Enter your code here. Read input from STDIN. Print output to STDOUT
puts ('Primitive : double')
puts('Primitive : char')
puts('Primitive : boolean')
puts('Primitive : int')
puts('Referenced : String')
puts('Primitive : boolean')
puts('Primitive : double')
puts('Primitive : char')
puts('Referenced : String')